### ISSUE TITLE
Images not found

### ISSUE THREAD

**Issue by OkomoJacob** [jkuatagges/AggesWebsiteChallenge2021#13]
- [ ] The website cannot find the direct URL to some images, kindly fix the bug

**Comment by samyberkane04** [comment]
@OkomoJacob 
hello 
can I contribute on this issue, please ?
thank you.

**Comment by alfredamboka** [comment]
@samyberkane04  
You can help me check this issue.

**Comment by alfredamboka** [comment]
@OkomoJacob 
I am checking the image links.

**Comment by OkomoJacob** [comment]
Hello @samyberkane04 and thank you so much for showing interest to play a key role to ensure we inly push clean code to prod.
However, this is a departmental ( Academic related) project and we will be happy to have you on board,  but you'll work under @alfredamboka supervision. You'll propose your changes from your patch then do a PR to @alfredamboka 's branch, he'll approve your changes or ask for change bf he can make a final PR to the main branch, just to ensure that things are OK, you can find my contacts and reach me out later [from my website](https://okomojacob.herokuapp.com). 
- Thanks
